[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
normal = { family = "ComicShannsMono Nerd Font" }
size = 15

[general]
import = ["~/.config/alacritty/themes/gruvbox_material.toml"]
