local M = {
  clipboard = "unnamedplus",
  colorcolumn = "80",
  completeopt = "menu",
  cursorline = true,
  expandtab = true,
  guicursor = "i:block",
  hlsearch = false,
  laststatus = 3,
  number = true,
  relativenumber = true,
  scrolloff = 5,
  shiftwidth = 2,
  showmode = false,
  signcolumn = "yes",
  smartindent = true,
  softtabstop = 2,
  splitbelow = true,
  splitright = true,
  tabstop = 2,
  termguicolors = true,
  wrap = false,
}

return M
