#!/usr/bin/env runhaskell

import System.Environment

printFileContents :: FilePath -> IO ()
printFileContents path = readFile path >>= putStr

printUsage :: String -> IO ()
printUsage progName = putStrLn $ "Usage: " ++ progName ++ " FILE"

main :: IO ()
main = do
    args <- getArgs
    if length args == 1
        then printFileContents $ head args
        else getProgName >>= printUsage
