#!/usr/bin/env python3

import sys

RTG_SUPPLIES = {
    "gas": {
        "argon": 1,
        "hydrogen": 1,
        "nitrogen": 1,
        "helium": 1,
    },
    "raw": {
        "ammonium": 2,
        "graphite": 1,
        "hematite": 1,
        "lithium": 1,
        "organic": 1,
        "titanite": 1,
    },
}


def print_item(item: tuple[str, int], rtg_count: int) -> None:
    print(f"{item[0].title()}: {item[1] * rtg_count}")


def print_materials(rtg_count: int) -> None:
    print("=== GASES ===\n")
    for item in RTG_SUPPLIES["gas"].items():
        print_item(item, rtg_count)

    print("\n=== RAW MATERIALS ===\n")
    for item in RTG_SUPPLIES["raw"].items():
        print_item(item, rtg_count)


print_materials(int(sys.argv[1]))
