#!/bin/sh

# I want to see all files, even hidden ones, when I'm in my dotfiles directory.
# They must be hidden since that's how stow works, but I still want to see them
# without having to add the -A flag myself every time.
case "$(pwd)" in
    *dotfiles*) flags='-A' ;;
    *) flags='' ;;
esac

ls $flags $@
