#!/usr/bin/env python3

import math
import sys

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} RADIUS")
    exit(1)

radius = int(sys.argv[1])
for z in range(radius):
    t = math.asin(z / (radius - 1))
    y = math.cos(t) * (radius - 1)
    for x in range(y):
        t2 = math.acos(x / (y - 1))
        y2 = math.sin(t2) * (y - 1)
        print(f"{y2:.0f}", end=" ")
    print()
