# Created by newuser for 5.8

alias grep='grep --color=auto'
alias ls='ls --color=auto'

alias vimrc='nvim ~/.config/nvim/init.vim'
alias zshrc='nvim ~/.zshrc'

NEWLINE=$'\n'
PS1="%B%F{1}%n%f at %F{3}%m%f in %F{2}%1~%f$NEWLINE%#%b "
