theme = "rose_pine"

[editor]
completion-trigger-len = 1
idle-timeout = 0
line-number = "relative"
rulers = [80, 120]

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "▏"
render = true
